name: pulseaudio
version: 0.1
summary: Audio framework (contains PulseAudio and alsa-lib) 
description: Contains PulseAudio and its dependencies, to
  enable apps to play back and record sound by talking to
  PulseAudio.

# sudo snappy hw-assign pulseaudio.sideload /dev/snd/controlC0
# sudo snappy hw-assign pulseaudio.sideload /dev/snd/pcmC0D0c
# sudo snappy hw-assign pulseaudio.sideload /dev/snd/pcmC0D0p
# sudo snappy hw-assign pulseaudio.sideload /dev/snd/timer
# export ALSA_CONFIG_PATH=/snaps/pulseaudio.sideload/current/usr/share/alsa/alsa.conf

apps:
  pulseaudio:
    command: pulseaudio --disable-shm=yes --exit-idle-time=-1 --disallow-exit=yes -vvvvnF $SNAP/etc/pulse/default.pa -p $SNAP/lib
    uses: [paserver-permissions]
  pactl:
    command: pactl
    uses: [paclient-permissions]
  pacat:
    command: pacat
    uses: [paclient-permissions]
  parecord:
    command: parecord
    uses: [paclient-permissions]
  paplay:
    command: paplay
    uses: [paclient-permissions]

uses:
  paclient-permissions:
    type: migration-skill
    security-override:
      socket: [/run/user/*/pulse/native]
      read-paths: [/run/user/*/pulse, /run/user/*/pulse/**]
      write-paths: [/run/user/*/pulse/native]
      syscalls: [sendto, recvfrom]

  paserver-permissions:
    type: migration-skill
    security-override:
      syscalls: [setpriority, bind, listen, sendto, recvfrom, accept4]
# listen needed to listen for client connections
# /run/udev/data (and bind) needed for scanning for sound cards
# /dev/snd needed for accessing the sound cards
# /run/dbus/system_bus_socket needed for Bluez 5
# /run/user/<uid>/pulse - that's where clients connect
      read-paths: [/run/udev/data/*, /dev/snd/control*, /dev/snd/pcm*, /run/user/*/pulse, /run/user/*/pulse/**]
      write-paths: [/dev/snd/control*, /dev/snd/pcm*, /run/user/*/pulse, /run/user/*/pulse/**]
      socket: [/run/user/*/pulse/native]

parts:
  pulseaudio:
    plugin: autotools
#    source: ../pkg-pulseaudio
    source-vcs: git
    source: git://anonscm.debian.org/pkg-pulseaudio/pulseaudio.git
    source-branch: ubuntu-snappy
    stage-packages: [libasound2-dev, libdbus-1-dev, libjson-c-dev, libglib2.0-dev,
       libspeexdsp-dev, libbluetooth-dev, libwebrtc-audio-processing-dev, libltdl-dev,
       libsndfile1-dev, libx11-xcb-dev, libx11-dev, libtdb-dev, libasyncns-dev, libxcb1-dev]
    build-packages: []
    configflags: [--disable-orc, --disable-gconf, --disable-bluez4, --disable-bluez5, --disable-esound,
       --disable-adrian-aec, --disable-gtk3, --disable-hal-compat, --disable-systemd-login]
  move-files:
    plugin: copy
    after: [pulseaudio]
    files:
      stage/lib/pulse-7.1/modules/*.so: lib/
      stage/lib/pulseaudio/libpulsecommon-7.1.so: lib/libpulsecommon-7.1.so

